---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

steps:
  - name: install
    image: node:14
    pull: if-not-exists
    commands:
      # try twice?
      - yarn install --pure-lockfile
      - yarn install --pure-lockfile
      - ls
    environment:
      NODE_ENV: production

  - name: build
    image: node:14
    privileged: true
    commands:
      - ls
      - yarn build
      - ls
    environment:
      NODE_ENV: production







