---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

steps:
  - name: install
    image: node:14
    pull: if-not-exists
    commands:
      # try twice?
      - npm i
      - ls
    environment:
      NODE_ENV: production







