---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

steps:
  - name: install
    image: node:14
    volumes:
      - name: nodemod
        path: /node_modules
    pull: if-not-exists
    commands:
      - yarn

  - name: build
    image: node:14
    volumes:
      - name: nodemod
        path: /node_modules
    commands:
      - yarn run build

  - name: publish
    failure: ignore
    image: plugins/gh-pages
    settings:
      pages_directory: dist/
      username:
        from_secret: github_token
        # drone-plugins/drone-gh-pages#16
      password: x-oauth-basic
    when:
      branch:
        - main
      event:
        exclude:
          - pull-request

volumes:
  - name: nodemod
    temp: {}
