---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

steps:
  - name: pre & build
    image: node
    pull: if-not-exists
    commands:
      - yarn
      - ls
        # - yarn gulp build
    environment:
      NODE_ENV: production
