---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

steps:
  - name: install
    image: node:14
    volumes:
      - name: nodemod
        path: /node_modules
    pull: if-not-exists
    commands:
      - npm i
      - ls

  - name: cry
    privileged: true
    image: node:14
    volumes:
      - name: nodemod
        path: /node_modules
    commands:
      - echo "You heard me. Start sobbing."
      - npm run build

volumes:
  - name: nodemod
    temp: {}
