---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

workspace:
  path: /drone/src

steps:
  - name: build
    image: node
    pull: if-not-exists
    commands:
      - yarn --cwd . --emoji true --pure-lockfile
      - ls
      - yarn build
    environment:
      NODE_ENV: production
