---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

workspace:
  path: /drone/src/

steps:
  - name: build
    image: node:14
    pull: if-not-exists
    commands:
      - yarn --cwd . --emoji true --pure-lockfile
        # ...where tf are we
      - echo $PWD
      - ls
      - yarn build
    environment:
      NODE_ENV: production
