---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

steps:
  - name: pre & build
    image: node
    commands:
      - npm i -g gulp-cli
      - gulp build
    environment:
      NODE_ENV: production
