---
kind: pipeline
type: docker
name: default

clone:
  depth: 2

workspace:
  path: /drone/src/

steps:
  - name: install
    image: node:14
    pull: if-not-exists
    commands:
      - yarn --pure-lockfile
      - ls
    environment:
      NODE_ENV: production

  - name: build
    image: node:14
    commands:
      - ls
      - yarn build
      - ls
    environment:
      NODE_ENV: production







