language: node_js
node_js: lts/*

cache: yarn

before_script:
  - npm i -g gulp-cli

script:
  - gulp build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: false
  deployment_file: true
  on:
    branch: main
